import { BusinessProfile, Client, Invoice, Payment, ProductService } from './types';

export const initialBusinessProfile: BusinessProfile = {
  businessName: 'Swapnil Creative & Tech Studio',
  ownerName: 'Swapnil',
  phone: '+91 98230 45678',
  email: 'swapnilshetty46@gmail.com',
  address: 'Shop 12, Pride Business Square, SB Road',
  cityState: 'Pune, Maharashtra 411016',
  taxId: 'GSTIN: 27AABCS8891P1ZK',
  bankName: 'HDFC Bank Ltd',
  accountNumber: '50200048921473',
  ifscCode: 'HDFC0000180',
  upiId: 'swapnil@okaxis',
  invoiceNotes: 'Thank you for your business! Payment is due within 7 days of invoice date.',
  currencySymbol: '₹',
};

export const initialClients: Client[] = [
  {
    id: 'client-1',
    name: 'Rajesh Shah',
    company: 'ABC Enterprises',
    phone: '+91 98231 11223',
    email: 'rajesh@abcenterprises.in',
    address: 'Plot 45, MIDC Industrial Area, Bhosari',
    cityState: 'Pune, Maharashtra',
    taxNumber: '27ABCDE1234F1Z5',
    notes: 'Regular corporate client. Net 15 payment terms.',
    createdAt: '2026-06-15',
  },
  {
    id: 'client-2',
    name: 'Neha Kulkarni',
    company: 'XYZ Services',
    phone: '+91 98200 77889',
    email: 'accounts@xyzservices.com',
    address: 'Level 5, Pinnacle Towers, BKC',
    cityState: 'Mumbai, Maharashtra',
    taxNumber: '27XYZDE5678G2Z1',
    notes: 'Digital marketing and monthly web maintenance retainer.',
    createdAt: '2026-07-02',
  },
  {
    id: 'client-3',
    name: 'Rahul Patil',
    company: 'Rahul Traders',
    phone: '+91 97654 33221',
    email: 'rahul@rahultraders.co.in',
    address: '108 Cotton Market Road',
    cityState: 'Nagpur, Maharashtra',
    taxNumber: '27RAHUL9988H3Z8',
    notes: 'Wholesale distributor. Always clears bills via UPI.',
    createdAt: '2026-08-10',
  },
  {
    id: 'client-4',
    name: 'Ananya Verma',
    company: 'Bright Horizon Academy',
    phone: '+91 99123 44556',
    email: 'info@brighthorizon.edu.in',
    address: 'Sector 14, Aundh',
    cityState: 'Pune, Maharashtra',
    taxNumber: '27BHAAC1122K4Z0',
    notes: 'Educational institution. Requires separate service breakdown.',
    createdAt: '2026-08-28',
  },
];

export const initialProducts: ProductService[] = [
  {
    id: 'prod-1',
    name: 'Website Design & Development',
    description: 'Custom responsive web application design & coding',
    defaultPrice: 20000,
    unit: 'Project',
  },
  {
    id: 'prod-2',
    name: 'Consulting & Strategy',
    description: 'Hourly technical consultation and architectural advisory',
    defaultPrice: 5000,
    unit: 'Session',
  },
  {
    id: 'prod-3',
    name: 'Monthly Maintenance',
    description: 'Server updates, security patches, content updates and backups',
    defaultPrice: 2000,
    unit: 'Month',
  },
  {
    id: 'prod-4',
    name: 'Graphic & Brand Design',
    description: 'Logos, marketing collateral, social media banners and branding assets',
    defaultPrice: 3500,
    unit: 'Package',
  },
  {
    id: 'prod-5',
    name: 'SEO & Performance Optimization',
    description: 'Search ranking improvements and site speed optimization',
    defaultPrice: 8000,
    unit: 'Audit',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1025',
    invoiceNumber: 'INV-1025',
    clientId: 'client-1',
    clientName: 'Rajesh Shah',
    clientCompany: 'ABC Enterprises',
    clientAddress: 'Plot 45, MIDC Industrial Area, Bhosari, Pune, Maharashtra',
    clientPhone: '+91 98231 11223',
    clientEmail: 'rajesh@abcenterprises.in',
    clientTaxNumber: '27ABCDE1234F1Z5',
    date: '2026-09-15',
    dueDate: '2026-09-22',
    items: [
      {
        id: 'item-1',
        description: 'Consulting & Strategic Roadmap',
        quantity: 2,
        price: 5000,
        amount: 10000,
      },
      {
        id: 'item-2',
        description: 'Monthly Maintenance Retainer (September)',
        quantity: 1,
        price: 5000,
        amount: 5000,
      },
    ],
    subtotal: 15000,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 15000,
    paidAmount: 15000,
    balanceDue: 0,
    status: 'paid',
    notes: 'Thank you for your prompt payment!',
    createdAt: '2026-09-15',
  },
  {
    id: 'inv-1024',
    invoiceNumber: 'INV-1024',
    clientId: 'client-2',
    clientName: 'Neha Kulkarni',
    clientCompany: 'XYZ Services',
    clientAddress: 'Level 5, Pinnacle Towers, BKC, Mumbai, Maharashtra',
    clientPhone: '+91 98200 77889',
    clientEmail: 'accounts@xyzservices.com',
    clientTaxNumber: '27XYZDE5678G2Z1',
    date: '2026-09-14',
    dueDate: '2026-09-21',
    items: [
      {
        id: 'item-3',
        description: 'Monthly Maintenance',
        quantity: 2,
        price: 2000,
        amount: 4000,
      },
      {
        id: 'item-4',
        description: 'Graphic & Brand Design - Autumn Campaign',
        quantity: 1,
        price: 3500,
        amount: 3500,
      },
      {
        id: 'item-5',
        description: 'Emergency Server Support',
        quantity: 1,
        price: 1000,
        amount: 1000,
      },
    ],
    subtotal: 8500,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 8500,
    paidAmount: 0,
    balanceDue: 8500,
    status: 'pending',
    notes: 'Payment is expected by 21st September 2026.',
    createdAt: '2026-09-14',
  },
  {
    id: 'inv-1023',
    invoiceNumber: 'INV-1023',
    clientId: 'client-3',
    clientName: 'Rahul Patil',
    clientCompany: 'Rahul Traders',
    clientAddress: '108 Cotton Market Road, Nagpur, Maharashtra',
    clientPhone: '+91 97654 33221',
    clientEmail: 'rahul@rahultraders.co.in',
    clientTaxNumber: '27RAHUL9988H3Z8',
    date: '2026-09-10',
    dueDate: '2026-09-17',
    items: [
      {
        id: 'item-6',
        description: 'SEO & Performance Optimization',
        quantity: 1,
        price: 8000,
        amount: 8000,
      },
      {
        id: 'item-7',
        description: 'Monthly Maintenance',
        quantity: 2,
        price: 2000,
        amount: 4000,
      },
    ],
    subtotal: 12000,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 12000,
    paidAmount: 12000,
    balanceDue: 0,
    status: 'paid',
    notes: 'Cleared via UPI transaction on 15th Sep.',
    createdAt: '2026-09-10',
  },
  {
    id: 'inv-1022',
    invoiceNumber: 'INV-1022',
    clientId: 'client-1',
    clientName: 'Rajesh Shah',
    clientCompany: 'ABC Enterprises',
    clientAddress: 'Plot 45, MIDC Industrial Area, Bhosari, Pune, Maharashtra',
    clientPhone: '+91 98231 11223',
    clientEmail: 'rajesh@abcenterprises.in',
    clientTaxNumber: '27ABCDE1234F1Z5',
    date: '2026-09-01',
    dueDate: '2026-09-15',
    items: [
      {
        id: 'item-8',
        description: 'Corporate Portal Redesign Phase 1',
        quantity: 1,
        price: 50000,
        amount: 50000,
      },
    ],
    subtotal: 50000,
    discountType: 'fixed',
    discountValue: 5000,
    discountAmount: 5000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 45000,
    paidAmount: 45000,
    balanceDue: 0,
    status: 'paid',
    notes: 'Completed Phase 1 deliverables.',
    createdAt: '2026-09-01',
  },
  {
    id: 'inv-1021',
    invoiceNumber: 'INV-1021',
    clientId: 'client-1',
    clientName: 'Rajesh Shah',
    clientCompany: 'ABC Enterprises',
    clientAddress: 'Plot 45, MIDC Industrial Area, Bhosari, Pune, Maharashtra',
    clientPhone: '+91 98231 11223',
    clientEmail: 'rajesh@abcenterprises.in',
    clientTaxNumber: '27ABCDE1234F1Z5',
    date: '2026-08-25',
    dueDate: '2026-09-08',
    items: [
      {
        id: 'item-9',
        description: 'Cloud Migration & Database Setup',
        quantity: 1,
        price: 20000,
        amount: 20000,
      },
    ],
    subtotal: 20000,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 20000,
    paidAmount: 0,
    balanceDue: 20000,
    status: 'overdue',
    notes: 'Payment is overdue by 9 days. Reminder sent.',
    createdAt: '2026-08-25',
  },
  {
    id: 'inv-1020',
    invoiceNumber: 'INV-1020',
    clientId: 'client-4',
    clientName: 'Ananya Verma',
    clientCompany: 'Bright Horizon Academy',
    clientAddress: 'Sector 14, Aundh, Pune, Maharashtra',
    clientPhone: '+91 99123 44556',
    clientEmail: 'info@brighthorizon.edu.in',
    clientTaxNumber: '27BHAAC1122K4Z0',
    date: '2026-08-18',
    dueDate: '2026-08-25',
    items: [
      {
        id: 'item-10',
        description: 'Website Design & Development',
        quantity: 1,
        price: 20000,
        amount: 20000,
      },
      {
        id: 'item-11',
        description: 'Maintenance',
        quantity: 2,
        price: 2000,
        amount: 4000,
      },
    ],
    subtotal: 24000,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 18,
    taxAmount: 4320,
    totalAmount: 28320,
    paidAmount: 28320,
    balanceDue: 0,
    status: 'paid',
    notes: 'Full payment received with GST.',
    createdAt: '2026-08-18',
  },
  {
    id: 'inv-1019',
    invoiceNumber: 'INV-1019',
    clientId: 'client-2',
    clientName: 'Neha Kulkarni',
    clientCompany: 'XYZ Services',
    clientAddress: 'Level 5, Pinnacle Towers, BKC, Mumbai, Maharashtra',
    clientPhone: '+91 98200 77889',
    clientEmail: 'accounts@xyzservices.com',
    clientTaxNumber: '27XYZDE5678G2Z1',
    date: '2026-08-10',
    dueDate: '2026-08-24',
    items: [
      {
        id: 'item-12',
        description: 'Consulting & Strategy (4 sessions)',
        quantity: 4,
        price: 5000,
        amount: 20000,
      },
    ],
    subtotal: 20000,
    discountType: 'percentage',
    discountValue: 0,
    discountAmount: 0,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 20000,
    paidAmount: 18500,
    balanceDue: 1500,
    status: 'overdue',
    notes: 'Partial payment of ₹18,500 received. Balance ₹1,500 overdue.',
    createdAt: '2026-08-10',
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-1',
    invoiceId: 'inv-1025',
    invoiceNumber: 'INV-1025',
    clientId: 'client-1',
    clientName: 'Rajesh Shah',
    clientCompany: 'ABC Enterprises',
    date: '2026-09-17',
    amount: 15000,
    method: 'Bank Transfer',
    referenceNumber: 'NEFT-HDFC-99381204',
    notes: 'Settled in full against INV-1025',
    createdAt: '2026-09-17',
  },
  {
    id: 'pay-2',
    invoiceId: 'inv-1023',
    invoiceNumber: 'INV-1023',
    clientId: 'client-3',
    clientName: 'Rahul Patil',
    clientCompany: 'Rahul Traders',
    date: '2026-09-15',
    amount: 12000,
    method: 'UPI',
    referenceNumber: 'UPI/22619088194',
    notes: 'Immediate UPI clearance',
    createdAt: '2026-09-15',
  },
  {
    id: 'pay-3',
    invoiceId: 'inv-1022',
    invoiceNumber: 'INV-1022',
    clientId: 'client-1',
    clientName: 'Rajesh Shah',
    clientCompany: 'ABC Enterprises',
    date: '2026-09-08',
    amount: 45000,
    method: 'Bank Transfer',
    referenceNumber: 'RTGS-ICIC-2938102',
    notes: 'Phase 1 development payment',
    createdAt: '2026-09-08',
  },
  {
    id: 'pay-4',
    invoiceId: 'inv-1020',
    invoiceNumber: 'INV-1020',
    clientId: 'client-4',
    clientName: 'Ananya Verma',
    clientCompany: 'Bright Horizon Academy',
    date: '2026-08-22',
    amount: 28320,
    method: 'Cheque',
    referenceNumber: 'CHQ-849201',
    notes: 'Cheque cleared successfully',
    createdAt: '2026-08-22',
  },
  {
    id: 'pay-5',
    invoiceId: 'inv-1019',
    invoiceNumber: 'INV-1019',
    clientId: 'client-2',
    clientName: 'Neha Kulkarni',
    clientCompany: 'XYZ Services',
    date: '2026-08-16',
    amount: 18500,
    method: 'UPI',
    referenceNumber: 'UPI/22510938812',
    notes: 'Part payment received',
    createdAt: '2026-08-16',
  },
];
